// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czlkdliwjyezugxrbzdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bGtkbGl3anllenVneHJiemR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjMzMDksImV4cCI6MjA1OTA5OTMwOX0.zVGUn_6iikC1JtigCxbAqO9FyfCr8vulRxbh2NwzlVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);